[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$SdkRoot,

    [string]$BuildDir,

    [string]$Generator = "Visual Studio 18 2026",

    [string]$Architecture = "x64",

    [switch]$Build,

    [string]$Configuration = "Debug"
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$sdkRootResolved = (Resolve-Path $SdkRoot).Path

if (-not $BuildDir) {
    $BuildDir = Join-Path $sdkRootResolved "_build_hot4d_vs18"
}

$cmakeCandidates = @(
    'cmake',
    'C:\Program Files\CMake\bin\cmake.exe',
    'C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe',
    'C:\Program Files\Microsoft Visual Studio\17\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe'
)

$cmakeExe = $null
foreach ($candidate in $cmakeCandidates) {
    if ($candidate -eq 'cmake') {
        $command = Get-Command cmake -ErrorAction SilentlyContinue
        if ($command) {
            $cmakeExe = $command.Source
            break
        }
    }
    elseif (Test-Path $candidate) {
        $cmakeExe = $candidate
        break
    }
}

if (-not $cmakeExe) {
    throw "Could not locate cmake.exe. Install CMake or Visual Studio CMake tools first."
}

$requiredSdkPaths = @(
    (Join-Path $sdkRootResolved 'CMakeLists.txt'),
    (Join-Path $sdkRootResolved 'cmake'),
    (Join-Path $sdkRootResolved 'frameworks')
)

$missing = $requiredSdkPaths | Where-Object { -not (Test-Path $_) }
if ($missing) {
    $formatted = ($missing | ForEach-Object { " - $_" }) -join [Environment]::NewLine
    throw "SDK root does not look complete. Missing required path(s):`n$formatted`nExpected an extracted Cinema 4D C++ SDK root containing at least CMakeLists.txt, cmake/, and frameworks/."
}

$customPathsFile = Join-Path $sdkRootResolved 'custom_paths_hot4d.txt'
$repoModulePath = ($repoRoot -replace '\\', '/')
Set-Content -Path $customPathsFile -Value @(
    '# Auto-generated by scripts/Configure-HOT4D-C4D2026SDK.ps1',
    "MODULE $repoModulePath"
)

Write-Host "Using CMake: $cmakeExe"
Write-Host "SDK root:    $sdkRootResolved"
Write-Host "Repo root:   $repoRoot"
Write-Host "Build dir:   $BuildDir"
Write-Host "Generator:   $Generator"
Write-Host "Arch:        $Architecture"
Write-Host "Custom paths file: $customPathsFile"

& $cmakeExe -S $sdkRootResolved -B $BuildDir -G $Generator -A $Architecture -D "MAXON_SDK_CUSTOM_PATHS_FILE=$customPathsFile"
if ($LASTEXITCODE -ne 0) {
    throw "CMake configure failed with exit code $LASTEXITCODE"
}

if ($Build) {
    & $cmakeExe --build $BuildDir --config $Configuration
    if ($LASTEXITCODE -ne 0) {
        throw "CMake build failed with exit code $LASTEXITCODE"
    }
}
